project:
  type: website

editor: visual

execute: 
  freeze: auto
  

website:
  title: "ISSS608 - VAA"
  sidebar:
    background: info
    tools: 
      - icon: house-fill
        href: "index.qmd"
      - icon: book
        href: "about.qmd"
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: "index.html"
      - section: "Hands On Exercise"
        contents: 
          - text: "Hands On Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands On Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - section: "Hands On Exercise 3"
            contents: 
              - text: "Hands On Exercise 3 Part A"
                href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
              - text: "Hands On Exercise 3 Part B"
                href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3B.html"
          - section: "Hands On Exercise 4"
            contents:
              - text: "Hands On Exercise 4 - Visualing Distribution"
                href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
              - text: "Hands On Exercise 4 - Visual Statistic Analysis"
                href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
              - text: "Hands On Exercise 4 - Visualising Uncertainty"
                href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
              - text: "Hands On Exercise 4 - Funnel Plots for Fair Comparisons"
                href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
          - section: "Hands On Exercise 5"
            contents: 
              - text: "Hands On Exercise 5 - Creating Ternary Plot with R"
                href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
              - text: "Hands On Exercise 5 - Visual Correlation Analysis"
                href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
              - text: "Hands On Exercise 5 - Heatmap for Visualising and Analysing Multivariate Data"
                href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html"
              - text: "Hands On Exercise 5 - Visual Multivariate Analysis with Parallel Coordinates Plot"
                href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html"
              - text: "Hands On Exercise 5 - Treemap Visualisation with R"
                href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html"
          - text: "Hands On Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/HandsonEx6.html"
          - section: "Hands On Exercise 7"
            contents:
              - text: "Hands On Exercise 7 - Choropleth Mapping with R"
                href: "Hands-on_Ex/Hands-on_Ex07/Handson_07a.html"
              - text: "Hands On Exercise 7b - Visualising Geospatial Point Data"
                href: "Hands-on_Ex/Hands-on_Ex07/Handson_07b.html"
              - text: "Hands On Exercise 7c - Analytical Mapping"
                href: "Hands-on_Ex/Hands-on_Ex07/Handson_07c.html"
          - text: "Hands On Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Handson08.html"

      - section: "Take Home Exercise"
        contents:
            - text: "Take Home Exercise 1"
              href: "Take_Home_Ex/Take_Home_Ex01/Take_Home_Ex01.html"
      - section: "Lesson Note"
        contents:
          - text: "TBC"
      
      
format: 
  html:
    css: styles.css 
    toc: true
    include-after-body:
      - text: |
          <style>
            .sparkle {
              position: absolute;
              pointer-events: none;
              background-image: url('/Images/troll.png');
              background-size: contain;
              background-repeat:no-repeat;
              border-radius: 50%;
              transform: translate(-50%, -50%);
              opacity: 0.9;
              animation: sparkle-fade 0.45s linear forwards;
              z-index: 9999;
            }
          
            @keyframes sparkle-fade {
              0% {
                transform: translate(-50%, -50%) scale(1);
                opacity: 0.9;
              }
              100% {
                transform: translate(-50%, -50%) scale(0.6);
                opacity: 0;
              }
            }
          </style>
          
          <script>
          (() => {
                if ("ontouchstart" in window) return;
                if (window.matchMedia("(prefers-reduced-motion)").matches) return;
              
                let lastTime = 0;
              
                function attachSparkles() {
                  document.addEventListener("mousemove", (e) => {
                    const now = performance.now();
                    if (now - lastTime < 18) return;
                    lastTime = now;
              
                    const sparkle = document.createElement("div");
                    sparkle.className = "sparkle";
                    sparkle.style.left = e.pageX + "px";
                    sparkle.style.top = e.pageY + "px";
                    
                    const size = Math.random() * 48 + 36;
                    sparkle.style.width = size + "px";
                    sparkle.style.height = size + "px";
              
                    document.body.appendChild(sparkle);
              
                    setTimeout(() => sparkle.remove(), 300);
                  });
                }
              
                window.addEventListener("DOMContentLoaded", attachSparkles);
                document.addEventListener("quarto:page-changed", attachSparkles);
              })();

          
          </script>


          

