project:
  type: website
  resources: 
    - site.js
    - images/troll.png
  
  

website:
  title: "ISSS608 - VAA"
  sidebar:
    tools: 
      - icon: house-fill
        href: "index.qmd"
      - icon: book
        href: "about.qmd"
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: "index.qmd"
      - section: "Hands On Exercise"
        contents:
          - text: "Hands On Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
          - text: "Hands On Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
          - text: "Hands On Exercise 3 Part A"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd"
          - text: "Hands On Exercise 3 Part B"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3B.qmd"
          - text: "Hands On Exercise 4 - Visualing Distribution"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.qmd"
          - text: "Hands On Exercise 4 - Visual Statistic Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.qmd"
          - text: "Hands On Exercise 4 - Visualising Uncertainty"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.qmd"
          - text: "Hands On Exercise 4 - Funnel Plots for Fair Comparisons"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.qmd"

      - section: "Lesson Note"
        contents:
          - text: "TBC"
      
      
format: 
  html:
    toc: true
    scripts:
      - site.js
    include-after-body:
      - text: |
          <style>
            .sparkle {
              position: absolute;
              pointer-events: none;
              background-image: url('Images/troll.png');
              background-size: contain;
              background-repeat:no-repeat;
              border-radius: 50%;
              transform: translate(-50%, -50%);
              opacity: 0.9;
              animation: sparkle-fade 0.45s linear forwards;
              z-index: 9999;
            }
          
            @keyframes sparkle-fade {
              0% {
                transform: translate(-50%, -50%) scale(1);
                opacity: 0.9;
              }
              100% {
                transform: translate(-50%, -50%) scale(0.6);
                opacity: 0;
              }
            }
          </style>
          
      
          
          

