---
title: "Hands-on_Ex02"
author: "Xi Zixun"
---

## Checking Required Packages

```{r}
pacman::p_load(ggrepel, patchwork, 
               ggthemes, tidyverse) 
```

## Data Loading

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

## Beyond ggplot2 Annotation : ggrepel

```{r}
#| echo: false
ggplot(data = exam_data,
       aes(x = MATHS,
       y = ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm,
              size=0.5) +
  geom_label(aes(label = ID),
             hjust= .5,
             vjust= .5) +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("English Score versus Maths Scores For Primary 3")
```

```{r}
#| echo: false
#| message: false
#| warning: false
ggplot(data = exam_data,
       aes(x = MATHS,
       y = ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm,
              size=0.5) +
  geom_label_repel(aes(label = ID),
             hjust= .5,
             vjust= .5) +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("English Score versus Maths Scores For Primary 3")
```

## From here onwards are Testing and others etc...

```{r}
library(ggplot2)

df <- data.frame(
  x = c(1, 1.05, 1.1),
  y = c(1, 1.05, 1.1),
  lab = c("A", "B", "C")
)

ggplot(df, aes(x, y, label = lab)) +
  geom_point(size = 3) +
  geom_label()


```

```{r}
library(ggrepel)

ggplot(df, aes(x, y, label = lab)) +
  geom_point(size = 3) +
  geom_label_repel()


```

```{r}
set.seed(123)
df2 <- data.frame(
  x = rnorm(50, 0, 0.05),
  y = rnorm(50, 0, 0.05),
  lab = paste0("P", 1:50)
)

ggplot(df2, aes(x, y, label = lab)) +
  geom_point() +
  geom_label_repel()

```
